code/hpxml_to_hescore.py
code/tests.py
docs/source/translation/hvac.rst
examples/house6.json
examples/house8.json
examples/house8.xml

for #45 
@lirainer it passes all the test cases we talked about. Testing code included.
@gmdickey This is the last time I rewrite HVAC organization. :-)

Splitting HVAC appropriately

---

hescorehpxml/__init__.py
tests/tests.py

Allowing hvac weights to be equal to 5% different

---

hescorehpxml/__init__.py
tests/tests.py

Duct location validation

---

docs/source/translation/about.rst
hescorehpxml/__init__.py
tests/tests.py

Added Comments

---

hescorehpxml/__init__.py
tests/tests.py

Allow more hvac combination

---

docs/source/translation/zone_roof.rst
hescorehpxml/__init__.py
tests/tests.py

Accounting for knee walls as attic floor area

---

hescorehpxml/__init__.py
tests/tests.py

Fixes #96 by changing the window code mappings for aluminum frame windows.

aluminum frame window code mappings

---

docs/source/translation/hpwes.rst
docs/source/translation/index.rst
hescorehpxml/__init__.py
tests/tests.py

HPwithES fields mapping from HPXML into HEScore

---

.circleci/config.yml
tests/tests.py

- Adds python 3.8 to CI.
- Fixes some deprecated assertions

Testing updates

---

docs/source/translation/hpwes.rst
hescorehpxml/__init__.py
tests/tests.py

Removing income eligible field from HPwES translation

---

hescorehpxml/__init__.py
tests/tests.py

better error for missing Slab element

---

docs/source/translation/about.rst

Updating docs to reflect actual translation of townhouse walls

---

docs/source/translation/hvac.rst
hescorehpxml/__init__.py
tests/tests.py

Hvac Weighting Priority

---

.gitignore
examples/house8.json
hescorehpxml/base.py
hescorehpxml/hpxml2.py
hescorehpxml/hpxml3.py
tests/test_translation.py

Area weighted R-value fix for knee walls

---

docs/source/translation/zone_roof.rst

Update knee walls documentation

---

examples/house6.xml
examples/house6_v3.xml
hescorehpxml/base.py
tests/test_translation.py

Fix cap of number of bedrooms

---

docs/source/translation/about.rst
docs/source/translation/building_address.rst
hescorehpxml/base.py
tests/test_translation.py

Move external_building_id to building_address element

---

hescorehpxml/hpxml3.py
tests/test_translation.py

Ignoring gable walls in hpxml v3 files

---

.github/workflows/build-test.yml
tests/test_scrub.py

Fixes #157
Makes the CI fail for all versions on test failure.

Failing CI on broken tests for all versions

---

examples/124-workflow-baseline-in.xml
examples/17-workflow-baseline-in.xml
examples/42-workflow-baseline-in.xml
hescorehpxml/hpxml3.py
tests/test_translation.py

Closes #155 
Add tests to verify handling of extra surfaces from ResStock HPXML files

Add tests for ResStock-HEScore

---

hescorehpxml/schemas/hescore_json.schema.json
tests/test_schema.py

Fixes #174 
Restrict the walls available for townhouses

Update schema for townhouse walls

---

docs/source/translation/hvac_distribution.rst
examples/hescore_min.json
examples/house1.json
examples/house2.json
examples/house3.json
examples/house4.json
examples/house5.json
examples/house6.json
examples/house8.json
examples/townhouse_walls.json
hescorehpxml/base.py
hescorehpxml/schemas/hescore_json.schema.json
tests/test_schema.py
tests/test_translation.py

Address NREL/OpenStudio-HEScore#280
Adds ability to accept CFM25 duct leakage to outside value (supply + return)

Duct blaster measurements

---

hescorehpxml/base.py
hescorehpxml/schemas/hescore_json.schema.json
tests/test_translation.py

Addresses #296
Make sure heating and cooling systems that are not allowed to have a distribution system don't have them.

Update hpxml2hescore duct validation

---

hescorehpxml/schemas/hescore_json.schema.json

Addresses https://github.com/NREL/OpenStudio-HEScore/issues/234#issuecomment-966475386
Add a new JSON element, storm_window_type

Low-e storms

---

hescorehpxml/schemas/hescore_json.schema.json
tests/test_schema.py

CEE HVAC efficiency levels

---

hescorehpxml/base.py
tests/test_scrub.py

The scrubbed hpxml file didn't have a complete customer in it causing the file not to validate.
```xml
<Customer>
<CustomerDetails>
<Person>
<SystemIdentifier id="Customer1"/>
</Person>
</CustomerDetails>
</Customer>
```
This changes it so that it now outputs
```xml
<Customer>
<CustomerDetails>
<Person>
<SystemIdentifier id="Customer1"/>
<Name>
<FirstName/>
<LastName/>
</Name>
</Person>
</CustomerDetails>
</Customer>
```
Added schema validation in testing to catch this in the future.

PII Scrubbing Validation

---

hescorehpxml/base.py
tests/test_translation.py

Allows for a PV tilt angle that is a real number

Improve PV tilt angle translation

---

hescorehpxml/schemas/hescore_json.schema.json
tests/test_schema.py

Fixes #
`below_other_unit` requires `ceiling_area` and disallows `ceiling_assembly_code` and `roof_area`

Update JSON Schema
