docs/source/translation/cooling_system.rst
docs/source/translation/heating_system.rst
hescorehpxml/__init__.py
tests/tests.py

This permits the case where a heatpump is specified but only provides cooling or heating. To specify that a heat pump only provides heating `HeatPump/FractionCoolLoadServed` must be present and equal to `0`. Likewise `HeatPump/FractionHeatLoadServed` must be present and equal to `0` if the heat pump only provides cooling.
This will pass through cases where a heat pump provides heating and a separate air conditioner provides cooling to HEScore. However, it will fail on the HEScore side because it cannot handle that configuration.

Allowing a heating- or cooling-only heat pump

---

docs/source/translation/heating_system.rst
docs/source/translation/zone_roof.rst
examples/hescore_min.xml
examples/house1-v2-2.xml
examples/house1.xml
examples/house3.xml
examples/house4.xml
examples/house5.xml
examples/house6.xml
examples/house7.xml
examples/house8.xml
examples/townhouse_walls.xml
hescorehpxml/__init__.py
hescorehpxml/schemas/hpxml-2.3.0/BaseElements.xsd
hescorehpxml/schemas/hpxml-2.3.0/HPXML.xsd
hescorehpxml/schemas/hpxml-2.3.0/HPXMLDataTypes.xsd
tests/tests.py

Updates the translator to use HPXML v2.3. Including the following translation changes:
- Translating the new `FloorFurnace` element into a `wall_furnace` in HEScore.
- Translating new "medium dark" `RoofColor`.
- Utilizing the new `Roof/SolarAbsorptance` element in HPXML to pass that through to HPXML when present.

Updating translator to work with hpxml v2.3

---

.circleci/config.yml
setup.py

Fixes #94 
This makes sure `future` is installed in the base installation as it should be.

Future py27

---

docs/source/translation/zone_roof.rst
hescorehpxml/__init__.py
tests/tests.py

Allow HEScore conditioned attic to be translated from HPXML 2.3.
Fix #95

Add cond_attic translation

---

hescorehpxml/__init__.py
hescorehpxml/__main__.py
tests/tests.py

In the calculation for adding knee wall area and R-value to to the attic floor, there was a divide by zero error on the UA calculation needed for that if the knee wall insulation R-value was zero or if the attic floor insulation R-value was zero. This fixes that.

Fix for knee wall R-value causing div by zero

---

hescorehpxml/__init__.py
tests/tests.py

This is in response to feeback that HPXML translation was failing for tankless water heaters. Indeed we weren't passing through the fuel type when we should have been.

Adding fuel type to tankless water heater

---

hescorehpxml/__init__.py
setup.py
tests/tests.py

This PR does a couple of things:
- Removes the "NREL Assumptions" code. We haven't used it in a long time and it's not relevant anymore.
- Catches more "element not found" errors and returns an error of which element is expected and missing.
- Finally, catches unexpected errors when run from the command line and gives a generic error message rather than a traceback.

Succeeding at failure

---

docs/source/translation/zone_window.rst
hescorehpxml/__init__.py
tests/tests.py

Fixes #111 
This PR changes the priority of how window orientation is determined to the following:
1. Check for `Azimuth`
2. Check for `Orientation`
3. Use azimuth or orientation of wall it is attached to. 
It also checks to make sure the wall referenced is indeed an above grade wall with an orientation. 
@shorowit, can you review?

Windows orientation priority

---

.circleci/config.yml
hescorehpxml/__init__.py
setup.py
tests/tests.py

For some reason, either in python3 or a newer version of lxml, the way we were reading in files from the command line no longer was able to be parsed by lxml. This was not caught by the tests because there were no tests on the CLI. This fixes the original problem _and_ adds a test for the CLI so we'll know if it regresses again.
cc @adamsten

Fixing CLI

---

.circleci/config.yml
hescorehpxml/__init__.py
hescorehpxml/base.py
setup.py
tests/test_scrub.py
tests/test_translation.py

Fixes #125.
This PR does the following:
- Adds a cli arg `--scrubbed-hpxml` to optionally export an HPXML file with PII removed.
- Switches the testing framework to pytest.
- Removes compatibility with Python 2.7. We were getting a lot of deprecation warnings in the testing. Python 2.7 [reached end of life on Jan 1, 2020](https://www.python.org/doc/sunset-python-2/), so it seems like this is an appropriate time to drop support.

Add export of HPXML file scrubbed of PII

---

docs/source/translation/zone_window.rst
hescorehpxml/base.py
tests/test_translation.py

Allow skylights to be assigned to the attached roofs if exist.
Fix #135

Skylight assignment

---

docs/source/translation/zone_wall.rst
hescorehpxml/base.py

Wall translation fixes and water heater EF rounding

---

docs/source/translation/hvac_distribution.rst
hescorehpxml/base.py
tests/test_translation.py

Fixes #141 
Map ducts with `DuctInsulationMaterial` that is not `None` to insulated ducts

Update duct insulation mapping

---

docs/source/translation/building_address.rst
hescorehpxml/base.py
tests/test_translation.py

Fixes #165
Previously this just passed whatever was in the `ZipCode` element in HPXML to HEScore. The HPXML element can include a zip plus 4 code. This strips it to just pass the 5 digit zip code.

Handle zip+4 in hpxml

---

hescorehpxml/base.py
tests/test_translation.py

Fixes #148
There was kind of a strange edge case where a wall could get a negative R-value if you specified XPS sheathing. This fixes that.
This branches off and will merge back into #160 because all the changes would conflict otherwise.

not allowing R-value to go past zero for walls with XPS

---

docs/source/translation/generation.rst
hescorehpxml/base.py
tests/test_translation.py

Fixes #178
Allows `NumberOfPanels` to be used directly from an HPXML (v3) file.

PV Number of Panels

---

docs/source/translation/hvac_distribution.rst
hescorehpxml/hpxml2.py
hescorehpxml/hpxml3.py
hescorehpxml/schemas/hescore_json.schema.json
tests/test_translation.py

Corresponding PR to https://github.com/NREL/OpenStudio-HEScore/pull/315, which allows additional duct locations.
For HPXML v3 files, the duct location map changes as follows:
HPXML | Previous HEScore Input | New HEScore Input
-- | -- | --
under slab | vented_crawl | under_slab
exterior wall | *not translated* | exterior_wall
roof deck | vented_crawl | outside
outside | vented_crawl | outside
For the three HPXML duct locations above that were previously mapped, this PR allows the building to no longer need a vented crawlspace foundation.
For HPXML v2 files, the duct location map changes as follows:
HPXML | Previous HEScore Input | New HEScore Input
-- | -- | --
outside | *not translated* | outside
PR Author: Check these when they're done. Not all may apply. ~~strikethrough~~ and check any …

Additional duct locations

---

docs/source/translation/hvac_distribution.rst
hescorehpxml/base.py
tests/test_translation.py

Update quantitative duct leakage modeling method to handle a case where duct leakage measurement for supply and return ducts are entered separately

Update duct blaster measurement

---

docs/source/translation/hvac_distribution.rst
hescorehpxml/hpxml2.py
tests/test_translation.py

Fixes #196
There was inconsistency between how HPXML v2 and v3 were handled with translating garages as foundation types and duct locations.All should be mapped to `unvented_crawl`, but it was mapping to `vented_crawl` in HPXML v2. Also, the docs incorrectly said it was being mapped to `vented_crawl` everywhere. This fixes all that.
@torstenglidden @lirainer

Updating garage duct location to unvented_crawl

---

examples/house7.xml
examples/house7_v3.xml
hescorehpxml/base.py
tests/test_translation.py

Fixes the issue where if there's a boiler, no cooling system, and a hydronic distribution system referenced we'd get an error. 

checking if distribution system returned before attaching
